language: php
php:
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - cp .env.travis .env
  - touch database/database.sqlite
  - php artisan migrate:install
  - php artisan migrate:refresh --seed
  - composer self-update
  - composer install --no-interaction

script:
- vendor/bin/phpunit
