# standard jekyll configuration

permalink: /articles/:title
pygments: true
exclude: ['Rakefile', 'config.rb', 'README.md','gems']
markdown: rdiscount

# configuration required for some pages

domain: nestor-qa.org
title: Nestor-QA project web page
author: The Nestor-QA team
email: no-x-spam@nestor-qa.com

# configuration for enhancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
    username: nestor-qa/nestor

#disqus:
#    id: disqusid
