front:
  build: .
  ports:
    - "8000:80"
    - "8443:443"
    - "9000:9000"
  links:
    - mysql:mysql
  volumes:
    - ./:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: nosecret
